### PR TITLE
refactor: Cleanup the XML layout files to get rid of hard coded values

### LINKED ISSUE #2: XML Code cleanup
There are so many hard coded values in the codebase, this should be extracted to appropriate resource files and where needed, make use of the tools:text attribute

### PR DESCRIPTION
**Pull request by mayorjay**
Closes #2 
@sunday58 do have a look at this PR

### CODE REVIEW

**Comment by sfxjolugbohunmi** [comment]
@sunday58 give me some time to resolve the conflicts

**Comment by mayorjay** [comment]
@sunday58 give me some time to resolve the conflicts

**Comment by mayorjay** [comment]
@sunday58 Conflicts resolved

**Comment by sunday58** [comment]
PR reviewed and merged

**Pull request merged**
